language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
os:
  - linux
before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb
  - sudo dkp-pacman -S devkitARM picasso tex3ds 3dstools devkit-env libctru citro3d citro2d 3ds-zlib 3ds-tinyxml2 3ds-mpg123 3ds-libpng --noconfirm
  - wget https://github.com/StuntHacks/m3diaLib/releases/download/v0.1.2-beta/build-v0.1.2-beta.zip -O build.zip
  - mkdir m3d-build
  - unzip build.zip -d m3d-build/
  - cd m3d-build/
  - sudo make install
  - cd ..
script:
  - make
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipents:
      - stunthacks@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    - DEVKITPRO="/opt/devkitpro"
    - DEVKITARM="/opt/devkitpro/devkitARM"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - unzip
      - imagemagick
      - gcc-5
      - g++-5
