language: cpp
dist: trusty
sudo: required
compiler:
  - gcc
os:
  - linux
before_install:
  - ./.travis.before_install.sh
script:
  - make
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipents:
      - stunthacks@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    - DEVKITPRO="/opt/devkitpro"
    - DEVKITARM="/opt/devkitpro/devkitARM"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - unzip
      - imagemagick
      - gcc-5
      - g++-5
